import { JobApplication } from "../types";

export const SampleJobApplications: JobApplication[] = [
  {
    id: 1,
    company: "Semantic Technologies",
    position: "Frontend Developer",
    location: "Whiskview",
    jobType: "Full-time",
    jobMode: "Remote",
    status: "Applied",
    appliedDate: new Date("2026-01-15"),
    latestUpdate: undefined,
    latestInterviewScheduledDate: undefined,
    referenceLink: "https://www.example.com",
  },
  {
    id: 2,
    company: "Papa's Global Ventures",
    position: "Software Engineer",
    location: "Tastyville",
    jobType: "Full-time",
    jobMode: "On-site",
    status: "Applied",
    appliedDate: new Date("2026-01-15"),
    latestUpdate: undefined,
    latestInterviewScheduledDate: undefined,
    referenceLink: "https://www.example.com",
  },
  {
    id: 3,
    company: "The Cone",
    position: "Full-Stack Web Developer",
    location: "Starlight City",
    jobType: "Full-time",
    jobMode: "On-site",
    status: "Applied",
    appliedDate: new Date("2026-01-16"),
    latestUpdate: undefined,
    latestInterviewScheduledDate: undefined,
    referenceLink: "https://www.example.com",
  },
  {
    id: 4,
    company: "MandiCo",
    position: "Junior Developer",
    location: "Starlight City",
    jobType: "Full-time",
    jobMode: "Hybrid",
    status: "Shortlisted",
    appliedDate: new Date("2026-01-16"),
    latestUpdate: new Date("2026-01-22"),
    latestInterviewScheduledDate: new Date("2026-01-28"),
    referenceLink: "https://www.example.com",
  },
  {
    id: 5,
    company: "Gigaloaf Labs",
    position: "Apprenticeship, Web Experience",
    location: "Starlight City",
    jobType: "Internship",
    jobMode: "On-site",
    status: "Shortlisted",
    appliedDate: new Date("2026-01-18"),
    latestUpdate: new Date("2026-01-24"),
    latestInterviewScheduledDate: new Date("2026-01-29"),
    referenceLink: "https://www.example.com",
  },
  {
    id: 6,
    company: "Fluffmart",
    position: "Software Systems Developer",
    location: "Tastyville",
    jobType: "Contract",
    jobMode: "Remote",
    status: "Applied",
    appliedDate: new Date("2026-01-19"),
    latestUpdate: undefined,
    latestInterviewScheduledDate: undefined,
    referenceLink: "https://www.example.com",
  },
  {
    id: 7,
    company: "Lawton Mechatronics",
    position: "Automation Developer (Web)",
    location: "Whiskview",
    jobType: "Full-time",
    jobMode: "On-site",
    status: "Interviewed",
    appliedDate: new Date("2026-01-19"),
    latestUpdate: new Date("2026-01-26"),
    latestInterviewScheduledDate: new Date("2026-01-26"),
    referenceLink: "https://www.example.com",
  },
  {
    id: 8,
    company: "Little John's Home Design",
    position: "WordPress Developer",
    location: "Oniontown",
    jobType: "Full-time",
    jobMode: "Remote",
    status: "Shortlisted",
    appliedDate: new Date("2026-01-20"),
    latestUpdate: new Date("2026-01-25"),
    latestInterviewScheduledDate: new Date("2026-01-30"),
    referenceLink: "https://www.example.com",
  },
  {
    id: 9,
    company: "Janana Talent Management",
    position: "WordPress Developer",
    location: "Whiskview",
    jobType: "Full-time",
    jobMode: "Hybrid",
    status: "Applied",
    appliedDate: new Date("2026-01-20"),
    latestUpdate: undefined,
    latestInterviewScheduledDate: undefined,
    referenceLink: "https://www.example.com",
  },
  {
    id: 10,
    company: "Office of the Mayor",
    position: "Frontend Web Developer",
    location: "Tacodale",
    jobType: "Contract",
    jobMode: "Hybrid",
    status: "Applied",
    appliedDate: new Date("2026-01-20"),
    latestUpdate: undefined,
    latestInterviewScheduledDate: undefined,
    referenceLink: "https://www.example.com",
  },
];
